"use client";
import { createContext, useContext, useState, useEffect } from "react";

// ─── English ────────────────────────────────────────────────────────────────
const en = {
  tagline: "Travel Smarter",
  nav_book: "Book",
  nav_routes: "Routes",
  nav_track: "Track",
  nav_agencies: "Agencies",
  nav_about: "About",
  nav_help: "Help",
  nav_agency_login: "Agency Login",
  nav_book_now: "Book Now",

  // Hero
  hero_live: "Live · 142 buses on road now",
  hero_travels: "Cameroon Travels",
  hero_flip: ["Smarter", "Safer", "Together", "Forward"],
  hero_sub:
    "Book verified intercity buses in seconds. Pay with MTN or Orange Money. Your family travels with confidence.",
  hero_from: "FROM",
  hero_to: "TO",
  hero_date: "DATE",
  hero_select_city: "Select city",
  hero_search: "Search →",
  hero_chip1: "✓ MTN & Orange Money",
  hero_chip2: "✓ Instant SMS Ticket",
  hero_chip3: "✓ Free 2hr Cancellation",
  hero_chip4: "✓ 40+ Verified Agencies",
  hero_stat1: "Daily Departures",
  hero_stat2: "Agency Partners",
  hero_stat3: "Monthly Travelers",
  hero_stat4: "Satisfaction Rate",

  // Popular Routes
  pop_badge: "Most Booked",
  pop_title: "Popular Routes",
  pop_view_all: "View All →",
  pop_from: "From",
  pop_today: "Today",
  pop_tap: "Tap to see & book →",

  // How It Works
  hiw_badge: "Simple Process",
  hiw_title: "Booked in under",
  hiw_title2: "3 minutes.",
  hiw_cta: "Book Your Seat →",
  hiw_s1_title: "Choose Route & Date",
  hiw_s1_body:
    "Pick your cities and date. See all available buses, times, and ratings instantly.",
  hiw_s2_title: "Select Your Seat",
  hiw_s2_body:
    "Choose your exact seat on a live bus layout. Window, aisle, or front row — your call.",
  hiw_s3_title: "Pay & Receive Ticket",
  hiw_s3_body:
    "MTN Money, Orange Money, or card. SMS ticket delivered in under 30 seconds.",
  hiw_stat1: "Bus Agencies",
  hiw_stat2: "On Time",

  // Terminal
  term_badge: "Every Morning",
  term_l1: "500+ buses.",
  term_l2: "Every city.",
  term_l3: "Every day.",
  term_cta: "Explore All Routes →",

  // Diaspora section (home)
  dias_badge: "🌍 For the Diaspora",
  dias_title1: "Send your family",
  dias_title2: "on a safe journey.",
  dias_title3: "From anywhere.",
  dias_body:
    "Living in Paris, London, or Houston? Pay in euros or dollars. Your mother in Yaoundé receives the ticket on her phone. You watch her bus move in real-time.",
  dias_cta: "Book for Family →",
  dias_stat1: "Family trips/month",
  dias_stat2: "Happy families",
  dias_f1: "Pay in EUR, USD, GBP",
  dias_f2: "SMS ticket to family",
  dias_f3: "Live GPS tracking",
  dias_f4: "Free cancellation",

  // Trust
  trust_badge: "Why JEMIL",
  trust_title1: "Why 10,000 travelers",
  trust_title2: "trust us every month.",
  trust_s1_v: "40+",
  trust_s1_k: "Verified Agencies",
  trust_s1_b: "Every agency licensed, inspected, and rated by real passengers.",
  trust_s2_v: "99%",
  trust_s2_k: "On-Time Record",
  trust_s2_b: "Real departure data — no guessing when to show up.",
  trust_s3_v: "24/7",
  trust_s3_k: "Live Support",
  trust_s3_b: "WhatsApp, phone, chat — always someone ready to help.",
  trust_s4_v: "<1hr",
  trust_s4_k: "Refund Speed",
  trust_s4_b: "Mobile money refunds arrive in under an hour.",
  trust_quote:
    "I booked my grandmother a ticket from Paris in 3 minutes. She arrived safely. I watched it live.",
  trust_attr: "— Marie T., Paris · JEMIL Diaspora User",

  // Final CTA
  cta_ready: "Ready to travel?",
  cta_book: "Book now.",
  cta_sub: "Join thousands of Cameroonians who travel smarter every day.",
  cta_btn1: "Book a Seat →",
  cta_btn2: "See All Routes",

  // Routes page
  routes_badge: "Cameroon Network",
  routes_title: "All Routes",
  routes_sub: (n) =>
    `${n} routes connecting Cameroon's major cities. Updated in real-time.`,
  routes_all_dep: "All departures",
  routes_all_dest: "All destinations",
  routes_clear: "✕ Clear",
  routes_map: "Route Map",
  routes_map_hint: "Hover a route to highlight",
  routes_found: (n) => `${n} routes found`,
  routes_popular: "Popular",
  routes_buses_day: "Buses/day",
  routes_rating: "Rating",
  routes_from: "From",
  routes_book: "Book →",

  // Track page
  track_badge: "Live GPS",
  track_title: "Track Your Bus",
  track_sub:
    "Enter your ticket reference to see exactly where your bus is right now.",
  track_placeholder: "Ticket ref e.g. JML-2847",
  track_btn: "Track Now →",
  track_error: "Ticket reference not found. Try JML-2847 or JML-2641.",
  track_demo_hint: "Demo: try JML-2847 or JML-2641",
  track_live_pos: "Live Position",
  track_live: "LIVE",
  track_pct: (p) => `${Math.round(p)}% of journey complete`,
  track_journey: "Live Journey Status",
  track_eta: "Estimated Arrival In",
  track_status: "Status",
  track_agency: "Agency",
  track_seat: "Seat",
  track_driver: "Driver",
  track_plate: "Plate No.",
  track_departed: "Departed",
  track_arrives: "Arrives",
  track_whatsapp: "Share on WhatsApp",
  track_no_ticket: "Have a ticket?",
  track_no_ticket_body:
    "Enter your ticket reference above to track your bus in real-time.",
  track_pct_label: (p) => `${p}% complete`,
  track_click: "Click to track →",

  // Agencies page
  agencies_badge: "Our Partners",
  agencies_title: "Bus Agencies",
  agencies_sub: (n) =>
    `${n} verified agencies. Every partner is licensed by the Ministry of Transport and rated by real passengers.`,
  agencies_stat1: "Licensed Agencies",
  agencies_stat2: "Daily Buses",
  agencies_stat3: "Avg. Rating",
  agencies_stat4: "Verified",
  agencies_search: "Search agencies…",
  agencies_all_cities: "All Cities",
  agencies_all_types: "All Types",
  agencies_found: (n) => `${n} agencies found`,
  agencies_verified: "Ministry-verified",
  agencies_routes: "Routes",
  agencies_trips: "Total Trips",
  agencies_est: "Est.",
  agencies_book: (name) => `Book with ${name} →`,
  agencies_partner_title: "Are you a bus agency?",
  agencies_partner_sub: "Partner with JEMIL.",
  agencies_partner_body:
    "Join 40+ agencies already selling tickets through JEMIL. Increase your bookings, reduce empty seats, and get paid instantly.",
  agencies_f1: "Zero setup costs",
  agencies_f2: "Real-time seat management dashboard",
  agencies_f3: "Instant payment settlement (same day)",
  agencies_f4: "Free marketing & promotion on our platform",
  agencies_m1_v: "48h",
  agencies_m1_k: "To get listed",
  agencies_m2_v: "0 XAF",
  agencies_m2_k: "Setup fees",
  agencies_m3_v: "3%",
  agencies_m3_k: "Commission only",
  agencies_m4_v: "Same day",
  agencies_m4_k: "Payout time",
  agencies_apply: "Apply to Join →",

  // Help page
  help_badge: "We Are Here",
  help_title: "Help Center",
  help_sub: "Answers to every question. Real support when you need it.",
  help_live_chat: "Live Chat",
  help_live_reply: "Reply in 2 min",
  help_phone: "+237 6XX XXX XXX",
  help_phone_hours: "Mon–Sun 6am–10pm",
  help_email: "hello@jemil.cm",
  help_email_reply: "Reply in 4 hours",
  help_categories: "Categories",
  help_still: "Still need help?",
  help_form_body:
    "Send us a message and we will get back to you within 4 hours.",
  help_name_placeholder: "Your name",
  help_email_placeholder: "your@email.com",
  help_msg_placeholder: "Describe your issue or question…",
  help_send: "Send Message →",
  help_sending: "Sending…",
  help_sent_title: "Message sent!",
  help_sent_body: "We will reply within 4 hours.",
  help_cats: [
    "Booking",
    "Payment",
    "Cancellations & Refunds",
    "Tracking",
    "Diaspora",
  ],
  help_faq: [
    {
      cat: "Booking",
      q: "How do I book a bus ticket?",
      a: "Go to the Book page, choose your route, date, and passenger count. Select a bus, pick your seat, fill in your details, and pay. Your SMS ticket arrives in under 30 seconds.",
    },
    {
      cat: "Booking",
      q: "Can I book for someone else?",
      a: "Yes. Enter the traveller's name and phone number at checkout. The SMS ticket will be sent to their number.",
    },
    {
      cat: "Booking",
      q: "Can I choose my seat?",
      a: "Yes — every bus has an interactive seat map so you can pick your exact seat before paying.",
    },
    {
      cat: "Payment",
      q: "What payment methods do you accept?",
      a: "MTN Mobile Money, Orange Money, Visa, and Mastercard. For diaspora bookings we also accept PayPal, Stripe, and bank transfers in EUR/USD/GBP.",
    },
    {
      cat: "Payment",
      q: "Is my payment secure?",
      a: "All payments are encrypted with 256-bit SSL. Card payments are processed by Stripe (PCI-DSS Level 1).",
    },
    {
      cat: "Cancellations & Refunds",
      q: "Can I cancel my ticket?",
      a: "Yes, up to 2 hours before departure. Go to Track, find your booking, and tap 'Cancel'. Refunds arrive within 1 hour.",
    },
    {
      cat: "Cancellations & Refunds",
      q: "What if the bus is cancelled by the agency?",
      a: "You will be notified immediately by SMS and receive a full refund within 30 minutes, no questions asked.",
    },
    {
      cat: "Tracking",
      q: "How do I track my bus?",
      a: "Go to the Track page and enter your ticket reference (e.g. JML-2847). You will see a live map updated every 30 seconds.",
    },
    {
      cat: "Tracking",
      q: "Is tracking available for all routes?",
      a: "GPS tracking is available on all routes served by agencies with our tracking devices. Coverage exceeds 90% of departures.",
    },
    {
      cat: "Diaspora",
      q: "I live abroad — can I book for family in Cameroon?",
      a: "Yes. The Diaspora module lets you pay in EUR, USD, or GBP. Your family member receives the ticket by SMS and boards with the SMS code — no smartphone required.",
    },
    {
      cat: "Diaspora",
      q: "What currencies do you accept for diaspora bookings?",
      a: "EUR, USD, GBP, and XAF. Exchange rates are updated daily. You see the exact amount before confirming.",
    },
  ],

  // About page
  about_story_badge: "Our Story",
  about_story_h1: "We built JEMIL because we",
  about_story_h2: "missed the bus.",
  about_story_body:
    "Literally. Our founder Emmanuel couldn't get through to book a seat home for Christmas 2022. So he called his co-founder Grace, and they built what didn't exist: a modern, reliable way to book buses in Cameroon.",
  about_mission_h: "Our mission is simple:",
  about_mission_h2: "Connect Cameroon.",
  about_mission_p1:
    "Cameroon is a country of 27 million people spread across rainforest, savanna, and highlands. Families live hours apart. Students travel to study. Workers commute across regions.",
  about_mission_p2:
    "Bus travel is how Cameroon moves. But for too long, it's been chaotic — phone calls, cash queues, uncertainty. We're changing that with technology built for Cameroon.",
  about_card1_t: "Built in Cameroon",
  about_card1_b: "By Cameroonians, for Cameroonians",
  about_card2_t: "Diaspora-first",
  about_card2_b: "Designed for families separated by oceans",
  about_card3_t: "Mobile-first",
  about_card3_b: "93% of our users book on mobile",
  about_card4_t: "Mobile Money",
  about_card4_b: "MTN & Orange — how Cameroon pays",
  about_timeline_badge: "How we got here",
  about_team_badge: "The team",
  about_team_sub: "Cameroonians who got tired of the way things were.",
  about_values_badge: "What we stand for",
  about_val1_t: "Transparency",
  about_val1_b:
    "The price you see is the price you pay. No hidden fees, no surprises.",
  about_val2_t: "Safety First",
  about_val2_b:
    "We verify every agency, every driver, every bus. Your family's safety is our business.",
  about_val3_t: "African Excellence",
  about_val3_b:
    "We build for Africa, with African standards of warmth, community, and resilience.",
  about_timeline: [
    {
      year: "2022",
      title: "The idea",
      body: "Emmanuel misses his Christmas bus. Grace answers the call. JEMIL is born in a Yaoundé apartment.",
    },
    {
      year: "2023 Q1",
      title: "First 3 agencies",
      body: "General Express, Vatican Express, and Buca Voyages join. First 100 tickets sold.",
    },
    {
      year: "2023 Q3",
      title: "MTN Money integration",
      body: "Mobile money payments go live. Conversion jumps 340% overnight.",
    },
    {
      year: "2024",
      title: "10,000 monthly trips",
      body: "JEMIL serves every major route in Cameroon. Live tracking launches.",
    },
    {
      year: "2025",
      title: "Live tracking",
      body: "Real-time GPS for 90%+ of departures. Diaspora module launches.",
    },
    {
      year: "2026",
      title: "Today",
      body: "40+ agencies. 2M+ tickets sold. Expanding to Gabon and Nigeria.",
    },
  ],
  about_team_members: [
    {
      name: "Emmanuel Nkwain",
      role: "Co-Founder & CEO",
      city: "Yaoundé / London",
      bio: "Former logistics engineer at Bolloré Africa. Missed the Christmas bus. Built JEMIL.",
    },
    {
      name: "Grace Mbah",
      role: "Co-Founder & CTO",
      city: "Douala",
      bio: "Ex-MTN engineer. Built the mobile money integration in 72 hours. Doesn't sleep much.",
    },
    {
      name: "Paul Tanga",
      role: "Head of Agency Partnerships",
      city: "Bafoussam",
      bio: "Knows every bus terminal manager in Cameroon. Signs 3 agencies a week.",
    },
    {
      name: "Aminata Diallo",
      role: "Head of Design",
      city: "Paris / Douala",
      bio: "Diaspora Cameroonian. Designed JEMIL to feel like home, even from 10,000km away.",
    },
  ],

  // Diaspora page
  dias_page_badge: "Diaspora Module",
  dias_page_title: "Book a bus for your family from anywhere.",
  dias_page_body:
    "You're in Paris, New York, Brussels — your mother is in Bafoussam. Buy her a ticket in 3 minutes. Pay in euros. She boards with a simple SMS. You watch it live.",
  dias_page_cta: "Book for Family →",
  dias_page_learn: "How it works ↓",
  dias_chip1: "🔒 Stripe-secured",
  dias_chip2: "📲 SMS without smartphone",
  dias_chip3: "✅ Real-time notifications",
  dias_chip4: "💱 EUR, USD, GBP",
  dias_calc_title: "Calculate the cost",
  dias_calc_route: "Route",
  dias_calc_currency: "Your currency",
  dias_calc_you_pay: "You pay approximately",
  dias_calc_fee: (code, rate) =>
    `+ ${code} 1.50 service fee · Rate: 1 ${code} = ${rate} XAF`,
  dias_calc_book: "Book This Journey →",
  dias_process_badge: "Simple Process",
  dias_process_title: "How diaspora booking works",
  dias_step_label: (n) => `Step ${n}`,
  dias_steps: [
    {
      title: "Book from anywhere",
      body: "Pay with Stripe, PayPal, card, or bank transfer — in EUR, USD, GBP or XAF. No Cameroonian account needed.",
    },
    {
      title: "Relative gets an SMS",
      body: "Your family member receives an instant SMS with a QR code and unique boarding number. No app, no smartphone, no internet needed.",
    },
    {
      title: "Board the bus",
      body: "They show the SMS code or QR at the terminal. The agency agent scans it. Done. No paper, no cash.",
    },
    {
      title: "You get notified",
      body: "You receive real-time alerts when they board, when the bus departs, and when they arrive. Peace of mind, from anywhere.",
    },
  ],
  dias_pop_badge: "Most Booked",
  dias_pop_title: "Diaspora favourite routes",
  dias_pop_see: "See All Routes →",
  dias_pop_popular: "Popular",
  dias_pop_book: "Book →",
  dias_trust_title: "Your money is safe. Always.",
  dias_trust: [
    {
      t: "Stripe & PayPal",
      b: "All international payments processed by certified global providers. Funds held in escrow until travel is confirmed.",
    },
    {
      t: "Free Cancellation",
      b: "Cancel up to 2 hours before departure for a full refund — back to your original currency within 24h.",
    },
    {
      t: "One-Time QR Code",
      b: "Every ticket generates a unique, encrypted QR code that can only be used once at the correct terminal.",
    },
    {
      t: "Live GPS Tracking",
      b: "Track the bus in real-time from the moment it departs until arrival.",
    },
    {
      t: "WhatsApp Support",
      b: "Reach our team instantly via WhatsApp in English, French, or Cameroonian Pidgin.",
    },
    {
      t: "100% Verified Agencies",
      b: "Every partner is Ministry of Transport licensed, inspected annually, and rated by real passengers.",
    },
  ],
  dias_final_title: "Your family travels with you.",
  dias_final_body:
    "Over 2,000 diaspora Cameroonians use JEMIL every month to keep their families moving safely.",
  dias_final_cta: "Book for Family Now →",
  dias_testimonials: [
    {
      text: "Je vis à Paris depuis 5 ans. Avec JEMIL, j'ai réservé le bus de ma maman en 3 minutes depuis mon téléphone. Elle est arrivée saine et sauve.",
      author: "Serge K.",
      location: "Paris, France",
    },
    {
      text: "My sister was stranded in Douala and I'm in Houston. Booked her a ticket in minutes, she got the SMS, boarded safely. JEMIL is everything.",
      author: "Aline M.",
      location: "Houston, USA",
    },
    {
      text: "Avant, j'appelais 5 agences avant de trouver une place. Maintenant je réserve en 2 minutes depuis Bruxelles.",
      author: "Fabrice N.",
      location: "Brussels, Belgium",
    },
  ],

  // RouteModal
  modal_step1: "Overview",
  modal_step2: "Choose Bus",
  modal_step3: "Seat & Pay",
  modal_route_details: "Route Details",
  modal_available_buses: "Available Buses",
  modal_complete: "Complete Booking",
  modal_choose_bus: "Choose your bus",
  modal_seat_pay: "Seat & Payment",
  modal_duration: "Duration",
  modal_distance: "Distance",
  modal_buses_today: "Buses today",
  modal_from: "From",
  modal_select_date: "Select Travel Date",
  modal_agencies_on_route: "Available Agencies on this Route",
  modal_more_agencies: (n) => `+${n} more agencies`,
  modal_chip1: "✓ MTN & Orange Money",
  modal_chip2: "✓ Instant SMS Ticket",
  modal_chip3: "✓ Free Cancellation",
  modal_chip4: "✓ GPS Tracked",
  modal_see_buses: "See Available Buses →",
  modal_back: "← Back",
  modal_seats_left: "seats left",
  modal_per_seat: "XAF / seat",
  modal_select: "Select →",
  modal_pick_seat: "Pick your seat",
  modal_full_name: "Full Name",
  modal_name_ph: "e.g. Jean-Paul Nkwain",
  modal_phone: "Phone",
  modal_phone_ph: "+237 6XX XXX XXX",
  modal_pay: (price) => `Pay ${price} XAF →`,
  modal_err_name: "Please enter your name",
  modal_err_phone: "Please enter your phone number",
  modal_err_seat: "Please select a seat",
  modal_payment: "Payment",
  modal_mtn: "MTN Mobile Money",
  modal_orange: "Orange Money",
  modal_card: "Visa / Mastercard",
  modal_booked_title: "You're booked!",
  modal_booked_sub: (phone) => `Your ticket has been sent to ${phone} by SMS.`,
  modal_ticket: "JEMIL TICKET",
  modal_passenger: "Passenger",
  modal_agency: "Agency",
  modal_departure: "Departure",
  modal_date_label: "Date",
  modal_seat: "Seat",
  modal_close: "Close",
  modal_track: "Track Bus →",
  modal_driver_label: "DRIVER",
  modal_seat_available: "Available",
  modal_seat_selected: "Selected",
  modal_seat_taken: "Taken",
  modal_processing: "Processing payment…",
  modal_please_wait: "Please wait, do not close this page.",

  // Backoffice
  bo_login_welcome: "Welcome back",
  bo_login_sub: "Sign in to manage your buses, manifests, and revenue.",
  bo_login_email: "Email",
  bo_login_pass: "Password",
  bo_login_email_ph: "ops@youragency.cm",
  bo_login_btn: "Sign In →",
  bo_login_not_agency: "Not an agency?",
  bo_login_apply: "Apply →",
  bo_login_admin: "Admin panel →",
  bo_login_err: "Please enter your credentials.",
  bo_portal: "Agency Portal",
  bo_sign_out: "Sign out",
  bo_live: "Live",
  bo_add_trip: "+ Add Trip",
  bo_nav: [
    "Overview",
    "Analytics",
    "Manifests",
    "Schedule",
    "Incidents",
    "Settings",
  ],
  bo_tickets_today: "Tickets Today",
  bo_revenue_today: "Revenue Today",
  bo_buses_op: "Buses Operating",
  bo_avg_occ: "Avg. Occupancy",
  bo_trust: "Trust Score",
  bo_revenue_trend: "Revenue Trend",
  bo_week_daily: "This week — daily revenue (XAF)",
  bo_vs_last: "↑ 22% vs last week",
  bo_bus_status: "Bus Status",
  bo_today: "Today",
  bo_on_road: "On Road",
  bo_boarding: "Boarding",
  bo_sold_out: "Sold Out",
  bo_available: "Available",
  bo_todays_dep: "Today's Departures",
  bo_see_all: "See all →",
  bo_manifest_btn: "📋 Manifest",
  bo_col_id: "ID",
  bo_col_route: "Route",
  bo_col_dep: "Dep.",
  bo_col_seats: "Seats",
  bo_col_fill: "Fill",
  bo_col_driver: "Driver",
  bo_col_class: "Class",
  bo_col_status: "Status",
  bo_col_action: "Action",
  bo_manifest_title: "Manifests",
  bo_passengers: (n) => `${n} passengers`,
  bo_export_csv: "📄 Export CSV",
  bo_print_pdf: "📑 Print PDF",
  bo_col_passenger: "Passenger",
  bo_col_phone: "Phone",
  bo_col_seat: "Seat",
  bo_col_payment: "Payment",
  bo_col_amount: "Amount (XAF)",
  bo_col_time: "Time",
  bo_seat_map: "Seat map",
  bo_sold: "Sold",
  bo_mani_available: "Available",
  bo_incident_title: "Incidents & Refunds",
  bo_approve_refund: "✓ Approve Refund",
  bo_reject: "✕ Reject",
  bo_msg_passenger: "💬 Message Passenger",
  bo_add_note: "📝 Add Note",
  bo_send_sms: "Send via SMS →",
  bo_msg_title: (name) => `Message ${name}`,
  bo_msg_ph: "Type your message…",
  bo_note_ph: "Add a note to this incident…",
  bo_note_save: "Save Note",
  bo_analytics_title: "Analytics",
  bo_months_12: "12 Months",
  bo_week_7: "This Week",
  bo_auto_refresh: "Auto-refreshes every 5 min",
  bo_monthly_revenue: "Monthly Revenue",
  bo_tickets_month: "Tickets / Month",
  bo_commission: "Commission (3%)",
  bo_refund_rate: "Refund Rate",
  bo_rev_ticket: "Revenue & Ticket Volume",
  bo_occ_rate: "Occupancy Rate %",
  bo_monthly_trend: "Monthly trend",
  bo_payment_methods: "Payment Methods",
  bo_rev_share: "Revenue share this month",
  bo_route_perf: "Route Performance",
  bo_tickets_per_route: "Tickets sold per route — last 30 days",
  bo_route_profit: "Route Profitability — Last 30 Days",
  bo_col_tickets: "Tickets",
  bo_col_revenue: "Revenue (XAF)",
  bo_col_occ: "Occupancy",
  bo_col_trend: "Trend",
  bo_last_payout: "Last Payout",
  bo_pending: "Pending Settlement",
  bo_commission_ded: "Commission Deducted",
  bo_net_month: "Net This Month",
  bo_schedule_title: "Schedule",
  bo_new_bus: "+ Schedule New Bus",
  bo_view_manifest: "📋 View Full Manifest",
  bo_update_price: "💱 Update Ticket Price",
  bo_create_promo: "🎁 Create Promo Code",
  bo_export_pax: "📤 Export Passenger List (.csv)",
  bo_cancel_refund: "❌ Cancel & Refund All",
  bo_apply: "✓ Apply",
  bo_copy: "Copy",
  bo_seat_map_label: (s, t) => `Seat Map (${s}/${t})`,
  bo_quick_actions: "Quick Actions",
  bo_price_ph: "New price XAF",
  bo_cancelled_msg: (sold) => `❌ CANCELLED — ${sold} refunds initiated`,
  bo_trip_modal_title: "Schedule New Bus",
  bo_trip_from: "From",
  bo_trip_to: "To",
  bo_trip_time: "Departure Time",
  bo_trip_seats: "Total Seats",
  bo_trip_price: "Seat Price (XAF)",
  bo_trip_driver: "Driver Name",
  bo_trip_plate: "Bus Plate",
  bo_trip_class: "Bus Class",
  bo_trip_standard: "Standard",
  bo_trip_vip: "VIP",
  bo_trip_submit: "Schedule Bus →",
  bo_trip_err: "Please fill in Departure, Destination, and Time.",
  bo_trip_from_ph: "Departure city",
  bo_trip_to_ph: "Arrival city",
  bo_trip_seats_ph: "e.g. 54",
  bo_trip_price_ph: "e.g. 4500",
  bo_trip_driver_ph: "Full name",
  bo_trip_plate_ph: "e.g. LT 0000 CM",
  bo_settings_title: "Agency Settings",
  bo_settings_profile: "Agency Profile",
  bo_settings_payout: "Payout Accounts",
  bo_settings_plan: "Current Plan",
  bo_settings_plan_name: "Pro Partner",
  bo_settings_plan_desc:
    "3% commission · Instant payouts · Priority listing · Full analytics",
  bo_settings_per_ticket: "per ticket sold",
  bo_settings_months: "Months Active",
  bo_settings_tickets: "Total Tickets",
  bo_settings_earned: "Net Earned",
  bo_settings_speed: "Payout Speed",
  bo_settings_save: "Save Changes",
  bo_settings_saved: "Saved!",
  bo_settings_active: "Active",
  bo_settings_edit: "Edit",
  bo_settings_fields: [
    "Agency Name",
    "HQ City",
    "Phone",
    "Email",
    "Founded",
    "License #",
  ],

  // Book page
  book_where_going: "Where are you going?",
  book_from: "From",
  book_to: "To",
  book_date: "Travel Date",
  book_passengers: "Passengers",
  book_passenger: "Passenger",
  book_search_btn: "Search Available Buses →",
  book_steps: ["Search", "Select Bus", "Choose Seat", "Payment", "Confirm"],
  book_back: "← Back",
  book_seats_left: "seats left",
  book_journey: "journey",
  book_choose_seat: "Choose your seat",
  book_your_selection: "Your selection",
  book_seat_number: "Seat number",
  book_seat_position: "Position",
  book_seat_window: "Window side",
  book_seat_aisle: "Aisle side",
  book_total: "Total",
  book_continue_payment: "Continue to Payment →",
  book_select_seat_hint: "Click a seat on the map to select it.",
  book_payment_title: "Payment & Details",
  book_payment_method: "Payment Method",
  book_passenger_details: "Passenger Details",
  book_full_name: "Full Name",
  book_phone: "Phone Number",
  book_email: "Email (optional)",
  book_order_summary: "Order Summary",
  book_route: "Route",
  book_date_label: "Date",
  book_agency: "Agency",
  book_departure: "Departure",
  book_seat: "Seat",
  book_pay_btn: "Pay",
  book_ssl: "🔒 Secured by 256-bit SSL encryption",
  book_processing: "Processing payment…",
  book_processing_sub: "Please wait, do not close this page.",
  book_error_name: "Please enter your full name",
  book_error_phone: "Please enter your phone number",
  book_youre_booked: "You're booked!",
  book_ticket_sent: "Your ticket has been sent via SMS and email.",
  book_back_home: "Back to Home",
  book_track_bus: "Track Bus →",
  book_ticket_label: "JEMIL TICKET",
  book_amount_paid: "Amount Paid",
  book_any_seat: "Any available",
  pay_mtn: "MTN Mobile Money",
  pay_mtn_desc: "Receive a prompt on your MTN number",
  pay_orange: "Orange Money",
  pay_orange_desc: "Receive a prompt on your Orange number",
  pay_card: "Visa / Mastercard",
  pay_card_desc: "Pay securely by card",

  // Common
  driver: "DRIVER",
  loading: "Loading…",
  xaf: "XAF",
  km: "km",
  buses: "buses",
};

// ─── French ─────────────────────────────────────────────────────────────────
const fr = {
  tagline: "Voyagez Mieux",
  nav_book: "Réserver",
  nav_routes: "Lignes",
  nav_track: "Suivre",
  nav_agencies: "Agences",
  nav_about: "À propos",
  nav_help: "Aide",
  nav_agency_login: "Espace Agence",
  nav_book_now: "Réserver",

  hero_live: "En direct · 142 bus sur la route",
  hero_travels: "Le Cameroun Voyage",
  hero_flip: ["Mieux", "Plus sûr", "Ensemble", "En avant"],
  hero_sub:
    "Réservez des bus intercités vérifiés en quelques secondes. Payez avec MTN ou Orange Money. Votre famille voyage en confiance.",
  hero_from: "DÉPART",
  hero_to: "ARRIVÉE",
  hero_date: "DATE",
  hero_select_city: "Choisir une ville",
  hero_search: "Rechercher →",
  hero_chip1: "✓ MTN & Orange Money",
  hero_chip2: "✓ Billet SMS instantané",
  hero_chip3: "✓ Annulation gratuite 2h",
  hero_chip4: "✓ 40+ Agences vérifiées",
  hero_stat1: "Départs quotidiens",
  hero_stat2: "Agences partenaires",
  hero_stat3: "Voyageurs / mois",
  hero_stat4: "Taux de satisfaction",

  pop_badge: "Les plus réservés",
  pop_title: "Lignes populaires",
  pop_view_all: "Voir tout →",
  pop_from: "Dès",
  pop_today: "Aujourd'hui",
  pop_tap: "Appuyer pour voir & réserver →",

  hiw_badge: "Simple et rapide",
  hiw_title: "Réservé en moins de",
  hiw_title2: "3 minutes.",
  hiw_cta: "Réserver ma place →",
  hiw_s1_title: "Choisissez la ligne et la date",
  hiw_s1_body:
    "Sélectionnez vos villes et la date. Voyez tous les bus disponibles, horaires et notes en temps réel.",
  hiw_s2_title: "Choisissez votre siège",
  hiw_s2_body:
    "Sélectionnez votre siège exact sur un plan de bus en direct. Fenêtre, couloir ou première rangée — c'est votre choix.",
  hiw_s3_title: "Payez et recevez votre billet",
  hiw_s3_body:
    "MTN Money, Orange Money ou carte. Billet SMS livré en moins de 30 secondes.",
  hiw_stat1: "Agences de bus",
  hiw_stat2: "À l'heure",

  term_badge: "Chaque matin",
  term_l1: "500+ bus.",
  term_l2: "Chaque ville.",
  term_l3: "Chaque jour.",
  term_cta: "Explorer toutes les lignes →",

  dias_badge: "🌍 Pour la Diaspora",
  dias_title1: "Envoyez votre famille",
  dias_title2: "en voyage en sécurité.",
  dias_title3: "De n'importe où.",
  dias_body:
    "Vous êtes à Paris, Londres ou Houston ? Payez en euros ou en dollars. Votre mère à Yaoundé reçoit le billet sur son téléphone. Vous suivez son bus en temps réel.",
  dias_cta: "Réserver pour la famille →",
  dias_stat1: "Voyages familiaux/mois",
  dias_stat2: "Familles satisfaites",
  dias_f1: "Payer en EUR, USD, GBP",
  dias_f2: "Billet SMS pour la famille",
  dias_f3: "Suivi GPS en direct",
  dias_f4: "Annulation gratuite",

  trust_badge: "Pourquoi JEMIL",
  trust_title1: "Pourquoi 10 000 voyageurs",
  trust_title2: "nous font confiance chaque mois.",
  trust_s1_v: "40+",
  trust_s1_k: "Agences vérifiées",
  trust_s1_b:
    "Chaque agence est licenciée, inspectée et notée par de vrais passagers.",
  trust_s2_v: "99%",
  trust_s2_k: "Ponctualité",
  trust_s2_b:
    "Données de départ réelles — plus besoin de deviner quand se présenter.",
  trust_s3_v: "24h/7",
  trust_s3_k: "Support en direct",
  trust_s3_b: "WhatsApp, téléphone, chat — toujours quelqu'un prêt à aider.",
  trust_s4_v: "<1h",
  trust_s4_k: "Remboursement rapide",
  trust_s4_b: "Les remboursements mobile money arrivent en moins d'une heure.",
  trust_quote:
    "J'ai réservé le bus de ma grand-mère depuis Paris en 3 minutes. Elle est arrivée saine et sauve. Je l'ai suivi en direct.",
  trust_attr: "— Marie T., Paris · Utilisatrice JEMIL Diaspora",

  cta_ready: "Prêt à voyager ?",
  cta_book: "Réservez maintenant.",
  cta_sub:
    "Rejoignez des milliers de Camerounais qui voyagent mieux chaque jour.",
  cta_btn1: "Réserver une place →",
  cta_btn2: "Voir toutes les lignes",

  routes_badge: "Réseau Cameroun",
  routes_title: "Toutes les lignes",
  routes_sub: (n) =>
    `${n} lignes reliant les principales villes du Cameroun. Mis à jour en temps réel.`,
  routes_all_dep: "Tous les départs",
  routes_all_dest: "Toutes les destinations",
  routes_clear: "✕ Effacer",
  routes_map: "Carte des lignes",
  routes_map_hint: "Survolez une ligne pour la mettre en évidence",
  routes_found: (n) => `${n} lignes trouvées`,
  routes_popular: "Populaire",
  routes_buses_day: "Bus/jour",
  routes_rating: "Note",
  routes_from: "Dès",
  routes_book: "Réserver →",

  track_badge: "GPS en direct",
  track_title: "Suivre votre bus",
  track_sub:
    "Entrez votre référence de billet pour voir exactement où se trouve votre bus en ce moment.",
  track_placeholder: "Réf. billet ex. JML-2847",
  track_btn: "Suivre →",
  track_error: "Référence introuvable. Essayez JML-2847 ou JML-2641.",
  track_demo_hint: "Démo : essayez JML-2847 ou JML-2641",
  track_live_pos: "Position en direct",
  track_live: "EN DIRECT",
  track_pct: (p) => `${Math.round(p)}% du trajet effectué`,
  track_journey: "Statut du trajet en direct",
  track_eta: "Arrivée estimée dans",
  track_status: "Statut",
  track_agency: "Agence",
  track_seat: "Siège",
  track_driver: "Chauffeur",
  track_plate: "Plaque",
  track_departed: "Départ",
  track_arrives: "Arrivée",
  track_whatsapp: "Partager sur WhatsApp",
  track_no_ticket: "Vous avez un billet ?",
  track_no_ticket_body:
    "Entrez votre référence de billet ci-dessus pour suivre votre bus en temps réel.",
  track_pct_label: (p) => `${p}% effectué`,
  track_click: "Cliquer pour suivre →",

  agencies_badge: "Nos Partenaires",
  agencies_title: "Agences de bus",
  agencies_sub: (n) =>
    `${n} agences vérifiées. Chaque partenaire est agréé par le Ministère des Transports et noté par de vrais passagers.`,
  agencies_stat1: "Agences agréées",
  agencies_stat2: "Bus quotidiens",
  agencies_stat3: "Note moy.",
  agencies_stat4: "Vérifiées",
  agencies_search: "Rechercher des agences…",
  agencies_all_cities: "Toutes les villes",
  agencies_all_types: "Tous les types",
  agencies_found: (n) => `${n} agences trouvées`,
  agencies_verified: "Agréé Ministère",
  agencies_routes: "Lignes",
  agencies_trips: "Voyages totaux",
  agencies_est: "Fondée",
  agencies_book: (name) => `Réserver avec ${name} →`,
  agencies_partner_title: "Vous êtes une agence de bus ?",
  agencies_partner_sub: "Rejoignez JEMIL.",
  agencies_partner_body:
    "Rejoignez plus de 40 agences qui vendent déjà leurs billets via JEMIL. Augmentez vos réservations, réduisez les sièges vides et soyez payé instantanément.",
  agencies_f1: "Aucun frais d'inscription",
  agencies_f2: "Tableau de bord de gestion des sièges en temps réel",
  agencies_f3: "Règlement instantané (le jour même)",
  agencies_f4: "Marketing et promotion gratuits sur notre plateforme",
  agencies_m1_v: "48h",
  agencies_m1_k: "Pour être référencé",
  agencies_m2_v: "0 XAF",
  agencies_m2_k: "Frais d'inscription",
  agencies_m3_v: "3%",
  agencies_m3_k: "Commission seulement",
  agencies_m4_v: "Même jour",
  agencies_m4_k: "Délai de paiement",
  agencies_apply: "Rejoindre JEMIL →",

  help_badge: "Nous sommes là",
  help_title: "Centre d'aide",
  help_sub:
    "Des réponses à toutes vos questions. Un vrai support quand vous en avez besoin.",
  help_live_chat: "Chat en direct",
  help_live_reply: "Réponse en 2 min",
  help_phone: "+237 6XX XXX XXX",
  help_phone_hours: "Lun–Dim 6h–22h",
  help_email: "hello@jemil.cm",
  help_email_reply: "Réponse en 4 heures",
  help_categories: "Catégories",
  help_still: "Besoin d'aide ?",
  help_form_body:
    "Envoyez-nous un message et nous vous répondrons dans les 4 heures.",
  help_name_placeholder: "Votre nom",
  help_email_placeholder: "votre@email.com",
  help_msg_placeholder: "Décrivez votre problème ou votre question…",
  help_send: "Envoyer →",
  help_sending: "Envoi en cours…",
  help_sent_title: "Message envoyé !",
  help_sent_body: "Nous vous répondrons dans les 4 heures.",
  help_cats: [
    "Réservation",
    "Paiement",
    "Annulations & Remboursements",
    "Suivi",
    "Diaspora",
  ],
  help_faq: [
    {
      cat: "Réservation",
      q: "Comment réserver un billet de bus ?",
      a: "Rendez-vous sur la page Réserver, choisissez votre ligne, la date et le nombre de passagers. Sélectionnez un bus, choisissez votre siège, renseignez vos coordonnées et payez. Votre billet SMS arrive en moins de 30 secondes.",
    },
    {
      cat: "Réservation",
      q: "Puis-je réserver pour quelqu'un d'autre ?",
      a: "Oui. Entrez le nom et le numéro de téléphone du voyageur lors du paiement. Le billet SMS lui sera envoyé directement.",
    },
    {
      cat: "Réservation",
      q: "Puis-je choisir mon siège ?",
      a: "Oui — chaque bus dispose d'un plan de sièges interactif pour que vous puissiez choisir votre place exacte avant de payer.",
    },
    {
      cat: "Paiement",
      q: "Quels modes de paiement acceptez-vous ?",
      a: "MTN Mobile Money, Orange Money, Visa et Mastercard. Pour les réservations diaspora, nous acceptons également PayPal, Stripe et les virements bancaires en EUR/USD/GBP.",
    },
    {
      cat: "Paiement",
      q: "Mon paiement est-il sécurisé ?",
      a: "Tous les paiements sont chiffrés avec SSL 256 bits. Les paiements par carte sont traités par Stripe (niveau PCI-DSS 1).",
    },
    {
      cat: "Annulations & Remboursements",
      q: "Puis-je annuler mon billet ?",
      a: "Oui, jusqu'à 2 heures avant le départ. Allez dans Suivi, trouvez votre réservation et appuyez sur « Annuler ». Les remboursements arrivent en moins d'une heure.",
    },
    {
      cat: "Annulations & Remboursements",
      q: "Que se passe-t-il si le bus est annulé par l'agence ?",
      a: "Vous êtes notifié immédiatement par SMS et remboursé intégralement en moins de 30 minutes, sans condition.",
    },
    {
      cat: "Suivi",
      q: "Comment suivre mon bus ?",
      a: "Rendez-vous sur la page Suivi et entrez votre référence de billet (ex. JML-2847). Vous verrez une carte en direct mise à jour toutes les 30 secondes.",
    },
    {
      cat: "Suivi",
      q: "Le suivi est-il disponible sur toutes les lignes ?",
      a: "Le suivi GPS est disponible sur toutes les lignes desservies par des agences équipées de nos dispositifs de suivi. La couverture dépasse 90 % des départs.",
    },
    {
      cat: "Diaspora",
      q: "Je vis à l'étranger — puis-je réserver pour ma famille au Cameroun ?",
      a: "Oui. Le module Diaspora vous permet de payer en EUR, USD ou GBP. Votre proche reçoit le billet par SMS et peut embarquer avec le code SMS — aucun smartphone requis.",
    },
    {
      cat: "Diaspora",
      q: "Quelles devises acceptez-vous pour les réservations diaspora ?",
      a: "EUR, USD, GBP et XAF. Les taux de change sont mis à jour quotidiennement. Vous voyez le montant exact avant de confirmer.",
    },
  ],

  about_story_badge: "Notre histoire",
  about_story_h1: "Nous avons créé JEMIL parce que nous avons",
  about_story_h2: "raté le bus.",
  about_story_body:
    "Littéralement. Notre fondateur Emmanuel n'a pas réussi à réserver une place pour rentrer chez lui à Noël 2022. Il a appelé sa co-fondatrice Grace, et ils ont créé ce qui n'existait pas : un moyen moderne et fiable de réserver des bus au Cameroun.",
  about_mission_h: "Notre mission est simple :",
  about_mission_h2: "Connecter le Cameroun.",
  about_mission_p1:
    "Le Cameroun est un pays de 27 millions d'habitants répartis entre forêt tropicale, savane et hauts plateaux. Les familles vivent à des heures les unes des autres. Les étudiants voyagent pour étudier. Les travailleurs font la navette entre les régions.",
  about_mission_p2:
    "Le bus est le mode de déplacement du Cameroun. Mais trop longtemps, c'était le chaos — appels téléphoniques, files d'attente, incertitude. Nous changeons ça avec une technologie conçue pour le Cameroun.",
  about_card1_t: "Fabriqué au Cameroun",
  about_card1_b: "Par des Camerounais, pour des Camerounais",
  about_card2_t: "Diaspora en priorité",
  about_card2_b: "Conçu pour les familles séparées par les océans",
  about_card3_t: "Mobile d'abord",
  about_card3_b: "93% de nos utilisateurs réservent sur mobile",
  about_card4_t: "Mobile Money",
  about_card4_b: "MTN & Orange — comment le Cameroun paie",
  about_timeline_badge: "Notre parcours",
  about_team_badge: "L'équipe",
  about_team_sub:
    "Des Camerounais qui en avaient assez des anciennes façons de faire.",
  about_values_badge: "Nos valeurs",
  about_val1_t: "Transparence",
  about_val1_b:
    "Le prix affiché est le prix payé. Aucuns frais cachés, aucune surprise.",
  about_val2_t: "Sécurité avant tout",
  about_val2_b:
    "Nous vérifions chaque agence, chaque chauffeur, chaque bus. La sécurité de votre famille est notre priorité.",
  about_val3_t: "Excellence africaine",
  about_val3_b:
    "Nous construisons pour l'Afrique, avec les standards africains de chaleur, de communauté et de résilience.",
  about_timeline: [
    {
      year: "2022",
      title: "L'idée",
      body: "Emmanuel rate son bus de Noël. Grace répond à l'appel. JEMIL naît dans un appartement de Yaoundé.",
    },
    {
      year: "2023 T1",
      title: "3 premières agences",
      body: "General Express, Vatican Express et Buca Voyages rejoignent la plateforme. Les 100 premiers billets sont vendus.",
    },
    {
      year: "2023 T3",
      title: "Intégration MTN Money",
      body: "Les paiements mobile money sont lancés. Le taux de conversion bondit de 340% en une nuit.",
    },
    {
      year: "2024",
      title: "10 000 voyages/mois",
      body: "JEMIL dessert toutes les grandes lignes du Cameroun. Le suivi en direct est lancé.",
    },
    {
      year: "2025",
      title: "Suivi GPS en direct",
      body: "GPS en temps réel pour plus de 90% des départs. Le module Diaspora est lancé.",
    },
    {
      year: "2026",
      title: "Aujourd'hui",
      body: "Plus de 40 agences. Plus de 2M de billets vendus. Extension au Gabon et au Nigeria.",
    },
  ],
  about_team_members: [
    {
      name: "Emmanuel Nkwain",
      role: "Co-Fondateur & PDG",
      city: "Yaoundé / Londres",
      bio: "Ancien ingénieur logistique chez Bolloré Africa. A raté le bus de Noël. A créé JEMIL.",
    },
    {
      name: "Grace Mbah",
      role: "Co-Fondatrice & CTO",
      city: "Douala",
      bio: "Ex-ingénieure MTN. A construit l'intégration mobile money en 72 heures. Ne dort pas beaucoup.",
    },
    {
      name: "Paul Tanga",
      role: "Responsable Partenariats Agences",
      city: "Bafoussam",
      bio: "Connaît tous les directeurs de gare routière au Cameroun. Signe 3 agences par semaine.",
    },
    {
      name: "Aminata Diallo",
      role: "Responsable Design",
      city: "Paris / Douala",
      bio: "Camerounaise de la diaspora. A conçu JEMIL pour que ça ressemble à chez soi, même à 10 000 km.",
    },
  ],

  dias_page_badge: "Module Diaspora",
  dias_page_title: "Réservez un bus pour votre famille depuis n'importe où.",
  dias_page_body:
    "Vous êtes à Paris, New York, Bruxelles — votre mère est à Bafoussam. Achetez-lui un billet en 3 minutes. Payez en euros. Elle embarque avec un simple SMS. Vous suivez tout en direct.",
  dias_page_cta: "Réserver pour la famille →",
  dias_page_learn: "Comment ça marche ↓",
  dias_chip1: "🔒 Sécurisé par Stripe",
  dias_chip2: "📲 SMS sans smartphone",
  dias_chip3: "✅ Notifications en temps réel",
  dias_chip4: "💱 EUR, USD, GBP",
  dias_calc_title: "Calculer le coût",
  dias_calc_route: "Ligne",
  dias_calc_currency: "Votre devise",
  dias_calc_you_pay: "Vous payez environ",
  dias_calc_fee: (code, rate) =>
    `+ ${code} 1,50 de frais · Taux : 1 ${code} = ${rate} XAF`,
  dias_calc_book: "Réserver ce voyage →",
  dias_process_badge: "Simple et rapide",
  dias_process_title: "Comment fonctionne la réservation diaspora",
  dias_step_label: (n) => `Étape ${n}`,
  dias_steps: [
    {
      title: "Réservez depuis n'importe où",
      body: "Payez avec Stripe, PayPal, carte ou virement — en EUR, USD, GBP ou XAF. Aucun compte camerounais requis.",
    },
    {
      title: "Votre proche reçoit un SMS",
      body: "Votre famille reçoit instantanément un SMS avec un QR code et un numéro d'embarquement unique. Pas d'appli, pas de smartphone.",
    },
    {
      title: "Il embarque dans le bus",
      body: "Il présente le code SMS ou le QR à la gare. L'agent de l'agence le scanne. C'est fait. Sans papier, sans espèces.",
    },
    {
      title: "Vous êtes notifié",
      body: "Vous recevez des alertes en temps réel à l'embarquement, au départ et à l'arrivée. La tranquillité d'esprit, de n'importe où.",
    },
  ],
  dias_pop_badge: "Les plus réservés",
  dias_pop_title: "Lignes favorites de la diaspora",
  dias_pop_see: "Voir toutes les lignes →",
  dias_pop_popular: "Populaire",
  dias_pop_book: "Réserver →",
  dias_trust_title: "Votre argent est en sécurité. Toujours.",
  dias_trust: [
    {
      t: "Stripe & PayPal",
      b: "Tous les paiements internationaux sont traités par des prestataires mondiaux certifiés. Les fonds sont conservés en séquestre jusqu'à confirmation du voyage.",
    },
    {
      t: "Annulation gratuite",
      b: "Annulez jusqu'à 2 heures avant le départ pour un remboursement intégral — dans votre devise d'origine sous 24h.",
    },
    {
      t: "QR code unique",
      b: "Chaque billet génère un QR code unique et chiffré, utilisable une seule fois au bon terminal.",
    },
    {
      t: "Suivi GPS en direct",
      b: "Suivez le bus en temps réel dès le départ jusqu'à l'arrivée.",
    },
    {
      t: "Support WhatsApp",
      b: "Contactez notre équipe instantanément via WhatsApp en anglais, français ou pidgin camerounais.",
    },
    {
      t: "100% Agences vérifiées",
      b: "Chaque partenaire est agréé par le Ministère des Transports, inspecté annuellement et noté par de vrais passagers.",
    },
  ],
  dias_final_title: "Votre famille voyage avec vous.",
  dias_final_body:
    "Plus de 2 000 Camerounais de la diaspora utilisent JEMIL chaque mois pour que leurs proches voyagent en sécurité.",
  dias_final_cta: "Réserver pour ma famille →",
  dias_testimonials: [
    {
      text: "Je vis à Paris depuis 5 ans. Avec JEMIL, j'ai réservé le bus de ma maman en 3 minutes depuis mon téléphone. Elle est arrivée saine et sauve.",
      author: "Serge K.",
      location: "Paris, France",
    },
    {
      text: "My sister was stranded in Douala and I'm in Houston. Booked her a ticket in minutes, she got the SMS, boarded safely. JEMIL is everything.",
      author: "Aline M.",
      location: "Houston, USA",
    },
    {
      text: "Avant, j'appelais 5 agences avant de trouver une place. Maintenant je réserve en 2 minutes depuis Bruxelles.",
      author: "Fabrice N.",
      location: "Bruxelles, Belgique",
    },
  ],

  modal_step1: "Aperçu",
  modal_step2: "Choisir le bus",
  modal_step3: "Siège & Paiement",
  modal_route_details: "Détails de la ligne",
  modal_available_buses: "Bus disponibles",
  modal_complete: "Finaliser la réservation",
  modal_choose_bus: "Choisissez votre bus",
  modal_seat_pay: "Siège & Paiement",
  modal_duration: "Durée",
  modal_distance: "Distance",
  modal_buses_today: "Bus aujourd'hui",
  modal_from: "Dès",
  modal_select_date: "Choisir la date de voyage",
  modal_agencies_on_route: "Agences disponibles sur cette ligne",
  modal_more_agencies: (n) => `+${n} autres agences`,
  modal_chip1: "✓ MTN & Orange Money",
  modal_chip2: "✓ Billet SMS instantané",
  modal_chip3: "✓ Annulation gratuite",
  modal_chip4: "✓ Suivi GPS",
  modal_see_buses: "Voir les bus disponibles →",
  modal_back: "← Retour",
  modal_seats_left: "sièges restants",
  modal_per_seat: "XAF / siège",
  modal_select: "Choisir →",
  modal_pick_seat: "Choisissez votre siège",
  modal_full_name: "Nom complet",
  modal_name_ph: "ex. Jean-Paul Nkwain",
  modal_phone: "Téléphone",
  modal_phone_ph: "+237 6XX XXX XXX",
  modal_pay: (price) => `Payer ${price} XAF →`,
  modal_err_name: "Veuillez entrer votre nom",
  modal_err_phone: "Veuillez entrer votre numéro",
  modal_err_seat: "Veuillez sélectionner un siège",
  modal_payment: "Paiement",
  modal_mtn: "MTN Mobile Money",
  modal_orange: "Orange Money",
  modal_card: "Visa / Mastercard",
  modal_booked_title: "Réservation confirmée !",
  modal_booked_sub: (phone) => `Votre billet a été envoyé au ${phone} par SMS.`,
  modal_ticket: "BILLET JEMIL",
  modal_passenger: "Passager",
  modal_agency: "Agence",
  modal_departure: "Départ",
  modal_date_label: "Date",
  modal_seat: "Siège",
  modal_close: "Fermer",
  modal_track: "Suivre le bus →",
  modal_driver_label: "CHAUFFEUR",
  modal_seat_available: "Disponible",
  modal_seat_selected: "Sélectionné",
  modal_seat_taken: "Occupé",
  modal_processing: "Traitement en cours…",
  modal_please_wait: "Veuillez patienter, ne fermez pas cette page.",

  bo_login_welcome: "Bon retour",
  bo_login_sub: "Connectez-vous pour gérer vos bus, manifestes et revenus.",
  bo_login_email: "Email",
  bo_login_pass: "Mot de passe",
  bo_login_email_ph: "ops@votreagence.cm",
  bo_login_btn: "Se connecter →",
  bo_login_not_agency: "Pas une agence ?",
  bo_login_apply: "Candidater →",
  bo_login_admin: "Panneau admin →",
  bo_login_err: "Veuillez entrer vos identifiants.",
  bo_portal: "Portail Agence",
  bo_sign_out: "Se déconnecter",
  bo_live: "En direct",
  bo_add_trip: "+ Ajouter un départ",
  bo_nav: [
    "Tableau de bord",
    "Analytiques",
    "Manifestes",
    "Programme",
    "Incidents",
    "Paramètres",
  ],
  bo_tickets_today: "Billets aujourd'hui",
  bo_revenue_today: "Revenus aujourd'hui",
  bo_buses_op: "Bus en opération",
  bo_avg_occ: "Taux d'occupation moy.",
  bo_trust: "Score de confiance",
  bo_revenue_trend: "Tendance des revenus",
  bo_week_daily: "Cette semaine — revenus quotidiens (XAF)",
  bo_vs_last: "↑ 22% vs semaine dernière",
  bo_bus_status: "Statut des bus",
  bo_today: "Aujourd'hui",
  bo_on_road: "En route",
  bo_boarding: "Embarquement",
  bo_sold_out: "Complet",
  bo_available: "Disponible",
  bo_todays_dep: "Départs du jour",
  bo_see_all: "Voir tout →",
  bo_manifest_btn: "📋 Manifeste",
  bo_col_id: "ID",
  bo_col_route: "Ligne",
  bo_col_dep: "Dép.",
  bo_col_seats: "Sièges",
  bo_col_fill: "Remplissage",
  bo_col_driver: "Chauffeur",
  bo_col_class: "Classe",
  bo_col_status: "Statut",
  bo_col_action: "Action",
  bo_manifest_title: "Manifestes",
  bo_passengers: (n) => `${n} passagers`,
  bo_export_csv: "📄 Exporter CSV",
  bo_print_pdf: "📑 Imprimer PDF",
  bo_col_passenger: "Passager",
  bo_col_phone: "Téléphone",
  bo_col_seat: "Siège",
  bo_col_payment: "Paiement",
  bo_col_amount: "Montant (XAF)",
  bo_col_time: "Heure",
  bo_seat_map: "Plan des sièges",
  bo_sold: "Vendus",
  bo_mani_available: "Disponibles",
  bo_incident_title: "Incidents & Remboursements",
  bo_approve_refund: "✓ Approuver le remboursement",
  bo_reject: "✕ Rejeter",
  bo_msg_passenger: "💬 Message Passager",
  bo_add_note: "📝 Ajouter une note",
  bo_send_sms: "Envoyer par SMS →",
  bo_msg_title: (name) => `Message à ${name}`,
  bo_msg_ph: "Tapez votre message…",
  bo_note_ph: "Ajouter une note à cet incident…",
  bo_note_save: "Enregistrer la note",
  bo_analytics_title: "Analytiques",
  bo_months_12: "12 mois",
  bo_week_7: "Cette semaine",
  bo_auto_refresh: "Actualisation automatique toutes les 5 min",
  bo_monthly_revenue: "Revenus mensuels",
  bo_tickets_month: "Billets / mois",
  bo_commission: "Commission (3%)",
  bo_refund_rate: "Taux de remboursement",
  bo_rev_ticket: "Revenus & Volume de billets",
  bo_occ_rate: "Taux d'occupation %",
  bo_monthly_trend: "Tendance mensuelle",
  bo_payment_methods: "Modes de paiement",
  bo_rev_share: "Part de revenus ce mois",
  bo_route_perf: "Performance des lignes",
  bo_tickets_per_route: "Billets vendus par ligne — 30 derniers jours",
  bo_route_profit: "Rentabilité des lignes — 30 derniers jours",
  bo_col_tickets: "Billets",
  bo_col_revenue: "Revenus (XAF)",
  bo_col_occ: "Occupation",
  bo_col_trend: "Tendance",
  bo_last_payout: "Dernier versement",
  bo_pending: "En attente de règlement",
  bo_commission_ded: "Commission déduite",
  bo_net_month: "Net ce mois",
  bo_schedule_title: "Programme",
  bo_new_bus: "+ Programmer un bus",
  bo_view_manifest: "📋 Voir le manifeste complet",
  bo_update_price: "💱 Modifier le tarif",
  bo_create_promo: "🎁 Créer un code promo",
  bo_export_pax: "📤 Exporter la liste passagers (.csv)",
  bo_cancel_refund: "❌ Annuler & Rembourser tous",
  bo_apply: "✓ Appliquer",
  bo_copy: "Copier",
  bo_seat_map_label: (s, tot) => `Plan sièges (${s}/${tot})`,
  bo_quick_actions: "Actions rapides",
  bo_price_ph: "Nouveau tarif XAF",
  bo_cancelled_msg: (sold) => `❌ ANNULÉ — ${sold} remboursements initiés`,
  bo_trip_modal_title: "Programmer un nouveau bus",
  bo_trip_from: "Départ",
  bo_trip_to: "Destination",
  bo_trip_time: "Heure de départ",
  bo_trip_seats: "Nombre de sièges",
  bo_trip_price: "Tarif du siège (XAF)",
  bo_trip_driver: "Nom du chauffeur",
  bo_trip_plate: "Plaque du bus",
  bo_trip_class: "Classe du bus",
  bo_trip_standard: "Standard",
  bo_trip_vip: "VIP",
  bo_trip_submit: "Programmer le bus →",
  bo_trip_err: "Veuillez renseigner le départ, la destination et l'heure.",
  bo_trip_from_ph: "Ville de départ",
  bo_trip_to_ph: "Ville d'arrivée",
  bo_trip_seats_ph: "ex. 54",
  bo_trip_price_ph: "ex. 4500",
  bo_trip_driver_ph: "Nom complet",
  bo_trip_plate_ph: "ex. LT 0000 CM",
  bo_settings_title: "Paramètres de l'agence",
  bo_settings_profile: "Profil de l'agence",
  bo_settings_payout: "Comptes de versement",
  bo_settings_plan: "Abonnement actuel",
  bo_settings_plan_name: "Pro Partenaire",
  bo_settings_plan_desc:
    "3% de commission · Versements instantanés · Référencement prioritaire · Analytiques complètes",
  bo_settings_per_ticket: "par billet vendu",
  bo_settings_months: "Mois actif",
  bo_settings_tickets: "Billets totaux",
  bo_settings_earned: "Net gagné",
  bo_settings_speed: "Rapidité de versement",
  bo_settings_save: "Enregistrer",
  bo_settings_saved: "Enregistré !",
  bo_settings_active: "Actif",
  bo_settings_edit: "Modifier",
  bo_settings_fields: [
    "Nom de l'agence",
    "Ville siège",
    "Téléphone",
    "Email",
    "Fondée en",
    "N° Licence",
  ],

  book_where_going: "Où allez-vous ?",
  book_from: "Départ",
  book_to: "Destination",
  book_date: "Date de voyage",
  book_passengers: "Passagers",
  book_passenger: "Passager",
  book_search_btn: "Rechercher les bus disponibles →",
  book_steps: ["Recherche", "Bus", "Siège", "Paiement", "Confirmation"],
  book_back: "← Retour",
  book_seats_left: "sièges restants",
  book_journey: "de trajet",
  book_choose_seat: "Choisissez votre siège",
  book_your_selection: "Votre sélection",
  book_seat_number: "Numéro de siège",
  book_seat_position: "Position",
  book_seat_window: "Côté fenêtre",
  book_seat_aisle: "Côté couloir",
  book_total: "Total",
  book_continue_payment: "Continuer vers le paiement →",
  book_select_seat_hint: "Cliquez sur un siège pour le sélectionner.",
  book_payment_title: "Paiement & Informations",
  book_payment_method: "Mode de paiement",
  book_passenger_details: "Informations passager",
  book_full_name: "Nom complet",
  book_phone: "Numéro de téléphone",
  book_email: "Email (optionnel)",
  book_order_summary: "Récapitulatif",
  book_route: "Itinéraire",
  book_date_label: "Date",
  book_agency: "Agence",
  book_departure: "Départ",
  book_seat: "Siège",
  book_pay_btn: "Payer",
  book_ssl: "🔒 Sécurisé par chiffrement SSL 256 bits",
  book_processing: "Traitement en cours…",
  book_processing_sub: "Veuillez patienter, ne fermez pas cette page.",
  book_error_name: "Veuillez entrer votre nom complet",
  book_error_phone: "Veuillez entrer votre numéro de téléphone",
  book_youre_booked: "Réservation confirmée !",
  book_ticket_sent: "Votre billet a été envoyé par SMS et email.",
  book_back_home: "Retour à l'accueil",
  book_track_bus: "Suivre le bus →",
  book_ticket_label: "BILLET JEMIL",
  book_amount_paid: "Montant payé",
  book_any_seat: "Disponible",
  pay_mtn: "MTN Mobile Money",
  pay_mtn_desc: "Recevez une notification sur votre numéro MTN",
  pay_orange: "Orange Money",
  pay_orange_desc: "Recevez une notification sur votre numéro Orange",
  pay_card: "Visa / Mastercard",
  pay_card_desc: "Payez en sécurité par carte",

  driver: "CHAUFFEUR",
  loading: "Chargement…",
  xaf: "XAF",
  km: "km",
  buses: "bus",
};

const LangContext = createContext({
  lang: "en",
  t: en,
  toggle: () => {},
  setLang: () => {},
});

export function LangProvider({ children }) {
  const [lang, setLang] = useState("en");
  useEffect(() => {
    const saved =
      typeof window !== "undefined" ? localStorage.getItem("jemil_lang") : null;
    if (saved === "fr" || saved === "en") setLang(saved);
  }, []);
  const toggle = () => {
    setLang((l) => {
      const next = l === "en" ? "fr" : "en";
      if (typeof window !== "undefined")
        localStorage.setItem("jemil_lang", next);
      return next;
    });
  };
  return (
    <LangContext.Provider
      value={{ lang, t: lang === "en" ? en : fr, toggle, setLang }}
    >
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
export { en, fr };
